{{- range $site := .Values.sites }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "checkmk.fullname" $ }}-{{ regexReplaceAll "[_\\W]+" $site.name "-" }}-http
  labels:
    {{- include "checkmk.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.http.type }}
  ports:
    - name: http
      {{- if .httpPortOverride }}
      port: {{ .httpPortOverride }}
      {{- else }}
      port: {{ $.Values.service.http.port }}
      {{- end }}
      targetPort: {{ $.Values.service.http.targetPort }}
      protocol: {{ $.Values.service.http.protocol }}
  selector:
    {{- include "checkmk.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/checkmk-site: {{ $site.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "checkmk.fullname" $ }}-{{ regexReplaceAll "[_\\W]+" $site.name "-" }}-livestatus
  labels:
    {{- include "checkmk.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.livestatus.type }}
  ports:
    - name: livestatus
      {{- if .liveStatusPortOverride }}
      port: {{ .liveStatusPortOverride }}
      {{- else }}
      port: {{ $.Values.service.livestatus.port }}
      {{- end }}
      targetPort: {{ $.Values.service.livestatus.targetPort }}
      protocol: {{ $.Values.service.livestatus.protocol }}
  selector:
    {{- include "checkmk.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/checkmk-site: {{ $site.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "checkmk.fullname" $ }}-{{ regexReplaceAll "[_\\W]+" $site.name "-" }}-tls
  labels:
    {{- include "checkmk.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.tls.type }}
  ports:
    - name: tls
      {{- if .tlsPortOverride }}
      port: {{ .tlsPortOverride }}
      {{- else }}
      port: {{ $.Values.service.tls.port }}
      {{- end }}
      targetPort: {{ $.Values.service.tls.targetPort }}
      protocol: {{ $.Values.service.tls.protocol }}
  selector:
    {{- include "checkmk.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/checkmk-site: {{ $site.name }}
---
{{- end }}