apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkmk-pv-claim
  namespace: checkmk
spec:
  # Please adjust to your system
  storageClassName: fast
  resources:
    requests:
      # Rather size larger for production environments
      storage: 16Gi
  accessModes:
    - ReadWriteOnce
