apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: checkmk
data:
# Uncomment and fill with own login credentials using: 
# kubectl create secret docker-registry regcred --docker-server=registry.checkmk.com --docker-username=<your-name> --docker-password=<your-pword>
# Get the secret in the right format to replace the next line with:
# kubectl get secret regcred --output=yaml
#  .dockerconfigjson: <registry-secret>
type: kubernetes.io/dockerconfigjson
