apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkmk
  name: checkmk
  namespace: checkmk
spec:
  # Multiple replicas are not supported at the moment
  replicas: 1
  selector:
    matchLabels:
      app: checkmk
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: checkmk
    spec:
      serviceAccount: checkmk
      containers:
      # For upadting Checkmk, just change the image. Don't downgrade between major versions
      - image: registry.checkmk.com/enterprise/check-mk-enterprise:2.0.0p5
        imagePullPolicy: IfNotPresent
        name: checkmk
        ports:
        - containerPort: 5000
          name: webport
          protocol: TCP
# Not supported at the moment
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 5000
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 5000
        resources:
# Not recommended to set
#          limits:
#            cpu:
#            memory:
          # Please adjust the requests to the size of your Checkmk instance. Rather increase then decrease the requests.
          requests:
            cpu: "2000m"
            memory: "4Gi"
        env:
        - name: CMK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: checkmk
              key: password
        - name: CMK_SITE_ID
          valueFrom:
            configMapKeyRef:
              name: checkmk
              key: siteid
        volumeMounts:
          - mountPath: "/omd/sites"
            name: checkmk-pv-storage
      restartPolicy: Always
      imagePullSecrets:
      - name: pull-secret
      securityContext: {}
      volumes:
# Requires a persistent volume
        - name: checkmk-pv-storage
          persistentVolumeClaim:
            claimName: checkmk-pv-claim
# In case no persistent volume available
#        - name: omd
#          emptyDir: {}
